### ISSUE TITLE
Minor cleanup post the PR merge - Typo in registration block text and the header links other than Contacts don't scroll page the page

### ISSUE THREAD

**Issue by dragon788** [DevOpsDaysDesMoines/DevOpsDaysDesMoines.github.io#3]
The header links other than Contacts don't scroll page the page

Registeration instead of correct spelling. @howkj1 @joshmccall221 

Also Sponsor seems to be a direct link, maybe we could make a Sponsorship section even if it is tiny to match the behavior of the other links. We could include the same specific sponsorship email that is on the DoD.org (DevOpsDays.org) event page.

Contact section talks about a project, should update that to something similar to what is on the DoD.org site about contacting the organizers for questions and see below

We probably want to use the event organizers' email address in the Contact section or a link to the DoD.org/eventname/contact page, see that page for the event specific email address.

**Comment by howkj1** [comment]
@dragon788 
> The header links other than Contacts don't scroll page the page
The scroll functionality is already wired up, but the section must exist for it to work. wink wink ;)

> Registeration instead of correct spelling. 
Fixed in upcoming commit.

> Also Sponsor seems to be a direct link, maybe we could make a Sponsorship section even if it is tiny to match the behavior of the other links. We could include the same specific sponsorship email that is on the DoD.org (DevOpsDays.org) event page.
Something better than nothing if people were actually hitting this site. Sure, we can whip up a separate section.

> Contact section talks about a project, should update that to something similar to what is on the DoD.org site about contacting the organizers for questions and see below
yeah, that was template leftovers...

> We probably want to use the event organizers' email address in the Contact section or a link to the DoD.org/eventname/contact page, see that page for the event specific email address.
Was working on linking to the organizer page instead since you are more likely to get spam with direct mailto:<>

**Comment by howkj1** [comment]
@dragon788 

see pull request
#5

**Comment by espoelstra** [comment]
Closed by #5 .
